name: semo
description: "A VOD streaming application"
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  envied: ^1.1.1
  firebase_analytics: ^11.5.0
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.7
  cloud_firestore: ^5.6.9
  firebase_remote_config: ^5.4.5
  flutter_settings_ui: ^3.0.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  google_sign_in: ^7.0.0
  http: ^1.4.0
  infinite_scroll_pagination: ^5.1.0
  internet_connection_checker_plus: ^2.7.2
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  subtitle_wrapper_package: ^2.2.1
  swipeable_page_route: ^0.4.7
  url_launcher: ^6.3.1
  wakelock_plus: ^1.3.2
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - fonts/
